"use client";

import {
  forwardRef,
} from "react";

type Props = {
  title: string;
  text: string;
  template: string;
};

const gradients: Record<
  string,
  string
> = {
  dark:
    "from-[#111827] via-[#1F2937] to-black",

  sunset:
    "from-[#7C3AED] via-[#EC4899] to-[#F43F5E]",

  ocean:
    "from-[#0F172A] via-[#0EA5E9] to-[#06B6D4]",

  forest:
    "from-[#052e16] via-[#166534] to-[#4d7c0f]",
};

const StoryCard = forwardRef<
  HTMLDivElement,
  Props
>(({ title, text, template }, ref) => {

  const bg =
    gradients[template] ||
    gradients.dark;

  return (
    <div
      ref={ref}
      className={`
        relative
        w-[340px]
        h-[600px]
        overflow-hidden
        rounded-[36px]
        bg-gradient-to-br
        ${bg}
        p-8
        shadow-2xl
        border border-white/10
      `}
    >

      {/* Glow */}
      <div className="absolute -top-20 left-1/2 h-72 w-72 -translate-x-1/2 rounded-full bg-white/10 blur-3xl" />

      {/* Extra Glow */}
      <div className="absolute bottom-0 right-0 h-56 w-56 rounded-full bg-pink-500/10 blur-3xl" />

      {/* Noise */}
      <div className="absolute inset-0 opacity-[0.04] bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />

      {/* Overlay */}
      <div className="absolute inset-0 bg-black/10" />

      {/* Content */}
      <div className="relative z-10 flex h-full flex-col justify-between">

        {/* Top */}
        <div>

          <div className="mb-5 inline-flex rounded-full border border-white/10 bg-white/10 px-4 py-1 text-xs tracking-[0.25em] text-white/70 backdrop-blur">
            THISME AI
          </div>

          <h1 className="text-[42px] leading-[1.05] font-black text-white whitespace-pre-wrap tracking-tight drop-shadow-xl">
            {title}
          </h1>

        </div>

        {/* Middle */}
        <div className="my-10 flex-1 flex items-center">

          <p className="text-[28px] leading-[1.6] text-white/90 whitespace-pre-wrap font-medium">
            {text}
          </p>

        </div>

        {/* Bottom */}
        <div className="flex items-end justify-between pt-6 border-t border-white/10">

          <div>

            <div className="text-xs uppercase tracking-[0.2em] text-white/40">
              Generated by
            </div>

            <div className="mt-1 text-lg font-bold tracking-wide text-white">
              THISME
            </div>

          </div>

          <div className="text-right">

            <div className="text-xs uppercase tracking-[0.2em] text-white/40">
              AI Personality
            </div>

            <div className="mt-1 text-sm text-white/70">
              Share Your Version
            </div>

          </div>

        </div>

      </div>

    </div>
  );
});

StoryCard.displayName =
  "StoryCard";

export default StoryCard;